<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Paciente;
use Illuminate\Support\Facades\DB;

class PacienteSeeder extends Seeder
{
    public function run(): void
    {
        $plan = DB::table('planes')->inRandomOrder()->first();
        $convenioId = $plan ? $plan->convenio_id : null;
        $planId = $plan ? $plan->id : null;

        $pacientes = [
            [
                'nombres' => 'Carlos',
                'apellidos' => 'Pérez Gómez',
                'tipo_documento' => '5',
                'documento' => '1002003001',
                'telefono' => '3001234567',
                'direccion' => 'Cra 10 #20-30',
                'email' => 'carlos@example.com',
                'fecha_nacimiento' => '1990-05-14',
                'sexo' => 'M',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'bucaramanga',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '1',
                'tipo_usuario' => '613',
                'observaciones' => 'Registro de prueba',
            ],
            [
                'nombres' => 'Ana',
                'apellidos' => 'Rodríguez López',
                'tipo_documento' => '5',
                'documento' => '1002003002',
                'telefono' => '3109876543',
                'direccion' => 'Cll 45 #12-34',
                'email' => 'ana@example.com',
                'fecha_nacimiento' => '1992-07-20',
                'sexo' => 'F',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'floridablanca',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '2',
                'tipo_usuario' => '613',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Julián',
                'apellidos' => 'Martínez Torres',
                'tipo_documento' => '4',
                'documento' => '1002003003',
                'telefono' => '3201112233',
                'direccion' => 'Av 30 #45-67',
                'email' => 'julian@example.com',
                'fecha_nacimiento' => '2010-02-05',
                'sexo' => 'M',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'bucaramanga',
                'zona_cod' => '20',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '0',
                'tipo_usuario' => '616',
                'observaciones' => 'Menor de edad',
            ],
            [
                'nombres' => 'Laura',
                'apellidos' => 'Castro Ramírez',
                'tipo_documento' => '5',
                'documento' => '1002003004',
                'telefono' => '3015556677',
                'direccion' => 'Cra 7 #65-12',
                'email' => 'laura@example.com',
                'fecha_nacimiento' => '1995-10-30',
                'sexo' => 'F',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '11',
                'municipio_residencia_cod' => 'bogota',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '1',
                'tipo_usuario' => '620',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Andrés',
                'apellidos' => 'García Peña',
                'tipo_documento' => '6',
                'documento' => '1002003005',
                'telefono' => '3027778899',
                'direccion' => 'Cll 80 #25-60',
                'email' => 'andres@example.com',
                'fecha_nacimiento' => '1993-03-12',
                'sexo' => 'M',
                'pais_nacimiento_cod' => '189',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'bucaramanga',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '0',
                'tipo_usuario' => '620',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Mariana',
                'apellidos' => 'Fernández Soto',
                'tipo_documento' => '5',
                'documento' => '1002003006',
                'telefono' => '3123334444',
                'direccion' => 'Cra 50 #20-15',
                'email' => 'mariana@example.com',
                'fecha_nacimiento' => '1991-08-09',
                'sexo' => 'F',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'bucaramanga',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '1',
                'tipo_usuario' => '613',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Esteban',
                'apellidos' => 'Ramírez Díaz',
                'tipo_documento' => '3',
                'documento' => '1002003007',
                'telefono' => '3004445555',
                'direccion' => 'Cll 100 #15-45',
                'email' => 'esteban@example.com',
                'fecha_nacimiento' => '2015-12-22',
                'sexo' => 'M',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'floridablanca',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '0',
                'tipo_usuario' => '616',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Paula',
                'apellidos' => 'Moreno Jiménez',
                'tipo_documento' => '5',
                'documento' => '1002003008',
                'telefono' => '3018889999',
                'direccion' => 'Cra 15 #50-20',
                'email' => 'paula@example.com',
                'fecha_nacimiento' => '1996-01-18',
                'sexo' => 'F',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '05',
                'municipio_residencia_cod' => 'medellin',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '2',
                'tipo_usuario' => '613',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Felipe',
                'apellidos' => 'Ortega Vargas',
                'tipo_documento' => '5',
                'documento' => '1002003009',
                'telefono' => '3122223333',
                'direccion' => 'Cll 25 #35-10',
                'email' => 'felipe@example.com',
                'fecha_nacimiento' => '1994-06-27',
                'sexo' => 'M',
                'pais_nacimiento_cod' => '1',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'bucaramanga',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '1',
                'tipo_usuario' => '613',
                'observaciones' => '',
            ],
            [
                'nombres' => 'Camila',
                'apellidos' => 'Rojas Cárdenas',
                'tipo_documento' => '7',
                'documento' => '1002003010',
                'telefono' => '3205556666',
                'direccion' => 'Av 68 #45-12',
                'email' => 'camila@example.com',
                'fecha_nacimiento' => '1997-09-03',
                'sexo' => 'F',
                'pais_nacimiento_cod' => '52',
                'pais_residencia_cod' => '1',
                'depto_residencia_cod' => '68',
                'municipio_residencia_cod' => 'bucaramanga',
                'zona_cod' => '19',
                'convenio_id' => $convenioId,
                'plan_id' => $planId,
                'rango' => '0',
                'tipo_usuario' => '620',
                'observaciones' => '',
            ],
        ];

        foreach ($pacientes as $data) {
            Paciente::updateOrCreate(
                ['email' => $data['email']],
                $data
            );
        }
    }
}